Style/AsciiComments:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'features/step_definitions/*.rb'
    - 'features/support/parameter_types.rb'
